---
title: "MNIST with H2O and RandomForest"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Learnt h2o usage from the below link
#https://www.analyticsvidhya.com/blog/2016/05/h2o-data-table-build-models-large-data-sets/

##RandomForest with untouched raw pixel image

```{r}
library(h2o)
train = read.csv("mnist_train.csv", header = TRUE)
test = read.csv("mnist_test.csv", header = TRUE)
h2o.init(nthreads = -1, max_mem_size = '4g', ip = "127.0.0.1", port = 50001)

train$class = as.factor(train$class)
test$class = as.factor(test$class)

train.h2o <- as.h2o(train)
test.h2o <- as.h2o(test)

T.dep <- 785
T.indep <- c(1:784)

#Tree 10, depth 4
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 10, max_depth = 4, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 10, depth 8
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o, ntrees = 10, max_depth = 8, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 10, depth 16
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 10, max_depth = 16, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 4
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 20, max_depth = 4, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 8
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 20, max_depth = 8, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 16
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 20, max_depth = 16, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 30, depth 4
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 30, max_depth = 4, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 30, depth 8
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 30, max_depth = 8, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 30, depth 16
model <- h2o.randomForest(y=T.dep, x=T.indep, training_frame = train.h2o,
                          ntrees = 30, max_depth = 16, seed = 1234)
preds <- as.data.frame(h2o.predict(model, newdata=test.h2o))
confusionMatrix <- table(test$class, as.vector(preds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy
```


##RandomForest with stretched bounding box

```{r}
library(h2o)
newtrain = read.csv("mnist_train_stretch.csv", header = TRUE)
newtest = read.csv("mnist_test_stretch.csv", header = TRUE)
h2o.init(nthreads = -1, max_mem_size = '4g', ip = "127.0.0.1", port = 50001)

newtrain$class = as.factor(newtrain$class)
newtest$class = as.factor(newtest$class)

newtrain.h2o <- as.h2o(newtrain)
newtest.h2o <- as.h2o(newtest)

nT.dep <- 401
nT.indep <- c(1:400)

#Tree 10, depth 4
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame = newtrain.h2o, ntrees = 10, max_depth = 4, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 10, depth 8
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                             newtrain.h2o, ntrees = 10, 
                             max_depth = 8, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 10, depth 16
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                             newtrain.h2o, ntrees = 10, max_depth = 16,
                             seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 4
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                             newtrain.h2o, ntrees = 20,
                             max_depth = 4, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 8
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                            newtrain.h2o, ntrees = 20,
                            max_depth = 8, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 20, depth 16
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                            newtrain.h2o, ntrees = 20,
                            max_depth = 16, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy


#Tree 30, depth 4
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                            newtrain.h2o, ntrees = 30,
                            max_depth = 4, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 30, depth 8
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                            newtrain.h2o, ntrees = 30,
                            max_depth = 8, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy

#Tree 30, depth 16
newmodel <- h2o.randomForest(y=nT.dep, x=nT.indep, training_frame =
                            newtrain.h2o, ntrees = 30,
                            max_depth = 16, seed = 120)
newpreds <- as.data.frame(h2o.predict(newmodel, newdata=newtest.h2o))
confusionMatrix <- table(newtest$class, as.vector(newpreds$predict))
accuracy <- sum(diag(confusionMatrix))/sum(confusionMatrix)
accuracy
```


